src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Entité représentant une adresse postale
 * 
 * Cette classe gère les adresses des utilisateurs, permettant de stocker
 * plusieurs adresses par utilisateur avec la possibilité de définir une adresse principale.
 */
#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    /**
     * Identifiant unique de l'adresse
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Nom de la rue
     * 
     * @var string|null La rue de l'adresse
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La rue est obligatoire")]
    private ?string $rue = null;

    /**
     * Code postal
     * 
     * @var string|null Le code postal de l'adresse (5 chiffres)
     */
    #[ORM\Column(length: 10)]
    #[Assert\NotBlank(message: "Le code postal est obligatoire")]
    #[Assert\Length(exactly: 5, exactMessage: "Le code postal doit contenir exactement 5 chiffres")]
    private ?string $codePostal = null;

    /**
     * Nom de la ville
     * 
     * @var string|null La ville de l'adresse
     */
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La ville est obligatoire")]
    private ?string $ville = null;

    /**
     * Complément d'adresse optionnel
     * 
     * @var string|null Informations supplémentaires (étage, bâtiment, etc.)
     */
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $complement = null;

    /**
     * Utilisateur associé à cette adresse
     * 
     * @var User|null Relation Many-To-One vers l'entité User
     */
    #[ORM\ManyToOne(inversedBy: 'adresses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * Indique si cette adresse est l'adresse principale de l'utilisateur
     * 
     * @var bool|null
     */
    #[ORM\Column]
    private ?bool $principale = false;

    /**
     * Récupère l'identifiant de l'adresse
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Récupère le nom de la rue
     */
    public function getRue(): ?string
    {
        return $this->rue;
    }

    /**
     * Définit le nom de la rue
     * 
     * @param string $rue La nouvelle rue
     */
    public function setRue(string $rue): static
    {
        $this->rue = $rue;
        return $this;
    }

    /**
     * Récupère le code postal
     */
    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    /**
     * Définit le code postal
     * 
     * @param string $codePostal Le nouveau code postal
     */
    public function setCodePostal(string $codePostal): static
    {
        $this->codePostal = $codePostal;
        return $this;
    }

    /**
     * Récupère le nom de la ville
     */
    public function getVille(): ?string
    {
        return $this->ville;
    }

    /**
     * Définit le nom de la ville
     * 
     * @param string $ville La nouvelle ville
     */
    public function setVille(string $ville): static
    {
        $this->ville = $ville;
        return $this;
    }

    /**
     * Récupère le complément d'adresse
     */
    public function getComplement(): ?string
    {
        return $this->complement;
    }

    /**
     * Définit le complément d'adresse
     * 
     * @param string|null $complement Le nouveau complément
     */
    public function setComplement(?string $complement): static
    {
        $this->complement = $complement;
        return $this;
    }

    /**
     * Récupère l'utilisateur associé à l'adresse
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * Définit l'utilisateur associé à l'adresse
     * 
     * @param User|null $user Le nouvel utilisateur
     */
    public function setUser(?User $user): static
    {
        $this->user = $user;
        return $this;
    }

    /**
     * Vérifie si l'adresse est principale
     */
    public function isPrincipale(): ?bool
    {
        return $this->principale;
    }

    /**
     * Définit si l'adresse est principale
     * 
     * @param bool $principale True si l'adresse est principale
     */
    public function setPrincipale(bool $principale): static
    {
        $this->principale = $principale;
        return $this;
    }

    /**
     * Génère une représentation textuelle complète de l'adresse
     * 
     * @return string L'adresse formatée avec tous ses composants
     */
    public function getAdresseComplete(): string
    {
        $adresse = $this->rue;
        if ($this->complement) {
            $adresse .= ', ' . $this->complement;
        }
        $adresse .= ', ' . $this->codePostal . ' ' . $this->ville;
        return $adresse;
    }
}

src/Entity/Fleur.php
<?php

namespace App\Entity;

use App\Repository\FleurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Entité représentant une fleur
 * 
 * Cette classe gère les informations relatives aux fleurs disponibles à la vente,
 * incluant leurs caractéristiques, prix, stock et relation avec le fleuriste.
 */
#[ORM\Entity(repositoryClass: FleurRepository::class)]
#[Vich\Uploadable]
class Fleur
{
    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }
    /**
     * Identifiant unique de la fleur
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Nom de la fleur
     * 
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    /**
     * Description détaillée de la fleur
     * 
     * @var string|null
     */
    #[ORM\Column(type: "text", nullable: true)]
    private ?string $description = null;


    /**
     * Prix de vente de la fleur
     * 
     * @var float|null
     */
    #[ORM\Column]
    private ?float $prix = null;

    /**
     * Quantité en stock
     * 
     * @var int|null
     */
    #[ORM\Column(nullable: true)]
    private ?int $stock = null;

    /**
     * Indique si la fleur est épinglée (mise en avant)
     * 
     * @var bool
     */
    #[ORM\Column(type: "boolean", options: ["default" => false])]
    private bool $isPinned = false;

    /**
     * Fleuriste vendant cette fleur
     * 
     * @var Fleuriste|null Relation Many-To-One vers l'entité Fleuriste
     */
    #[ORM\ManyToOne(targetEntity: Fleuriste::class, inversedBy: 'fleurs')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Fleuriste $fleuriste = null;

    /**
     * Fichier image téléchargé
     */
    #[Vich\UploadableField(mapping: 'fleur_images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    /**
     * Nom du fichier image
     */
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageName = null;

    /**
     * Date de dernière mise à jour
     */
    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    /**
     * Tags associés à cette fleur
     * 
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'fleurs')]
    private Collection $tags;

    /**
     * Commentaires sur cette fleur
     * 
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(mappedBy: 'fleur', targetEntity: Commentaire::class, orphanRemoval: true)]
    private Collection $commentaires;

    /**
     * Récupère l'identifiant de la fleur
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Récupère le nom de la fleur
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * Définit le nom de la fleur
     * 
     * @param string $nom Le nouveau nom
     */
    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    /**
     * Récupère la description de la fleur
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Définit la description de la fleur
     * 
     * @param string|null $description La nouvelle description
     */
    public function setDescription(?string $description): static
    {
        $this->description = $description;
        return $this;
    }


    /**
     * Récupère le prix de la fleur
     */
    public function getPrix(): ?float
    {
        return $this->prix;
    }

    /**
     * Définit le prix de la fleur
     * 
     * @param float $prix Le nouveau prix
     */
    public function setPrix(float $prix): static
    {
        $this->prix = $prix;
        return $this;
    }

    /**
     * Récupère la quantité en stock
     */
    public function getStock(): ?int
    {
        return $this->stock;
    }

    /**
     * Définit la quantité en stock
     * 
     * @param int|null $stock La nouvelle quantité
     */
    public function setStock(?int $stock): static
    {
        $this->stock = $stock;
        return $this;
    }

    /**
     * Vérifie si la fleur est épinglée
     */
    public function getIsPinned(): bool
    {
        return $this->isPinned;
    }

    /**
     * Définit si la fleur est épinglée
     * 
     * @param bool $isPinned True si la fleur doit être épinglée
     */
    public function setIsPinned(bool $isPinned): static
    {
        $this->isPinned = $isPinned;
        return $this;
    }

    /**
     * Récupère le fleuriste associé
     */
    public function getFleuriste(): ?Fleuriste
    {
        return $this->fleuriste;
    }

    /**
     * Définit le fleuriste associé
     * 
     * @param Fleuriste|null $fleuriste Le nouveau fleuriste
     */
    public function setFleuriste(?Fleuriste $fleuriste): self
    {
        $this->fleuriste = $fleuriste;
        return $this;
    }

    /**
     * Définit le fichier image
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    /**
     * Obtient le fichier image
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * Définit le nom de l'image
     */
    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    /**
     * Obtient le nom de l'image
     */
    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * Obtient l'URL de l'image
     */
    public function getImageUrl(): string
    {
        if ($this->imageName) {
            return '/uploads/fleurs/' . $this->imageName;
        }

        // Image aléatoire par défaut
        $images = ['flower1.jpg', 'flower2.jpg', 'flower3.jpg', 'flower4.jpg', 'flower5.jpg', 'flower6.jpg', 'flower7.jpg', 'flower8.jpg', 'flower9.jpg', 'flower10.jpg', 'flower11.jpg', 'flower12.jpg'];
        return '/img/flowerimg/' . $images[array_rand($images)];
    }

    /**
     * Détermine le statut du stock
     * 
     * @return string Le statut du stock ('out_of_stock', 'low_stock', 'medium_stock', 'in_stock')
     */
    public function getStockStatus(): string
    {
        if ($this->stock === null) {
            return 'unknown';
        }
        if ($this->stock === 0) {
            return 'out_of_stock';
        } elseif ($this->stock <= 10) {
            return 'low_stock';
        } elseif ($this->stock <= 50) {
            return 'medium_stock';
        } else {
            return 'in_stock';
        }
    }

    /**
     * Récupère le libellé du statut du stock
     * 
     * @return string Le libellé en français du statut du stock
     */
    public function getStockLabel(): string
    {
        return match ($this->getStockStatus()) {
            'out_of_stock' => 'Rupture de stock',
            'low_stock' => 'Stock faible',
            'medium_stock' => 'Stock moyen',
            'in_stock' => 'En stock',
            default => 'Statut inconnu'
        };
    }

    /**
     * Récupère la couleur associée au statut du stock
     * 
     * @return string La couleur correspondant au statut du stock
     */
    public function getStockColor(): string
    {
        return match ($this->getStockStatus()) {
            'out_of_stock' => 'red',
            'low_stock' => 'orange',
            'medium_stock' => 'yellow',
            'in_stock' => 'green',
            default => 'gray',
        };
    }

    /**
     * Récupère les tags associés à cette fleur
     * 
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    /**
     * Ajoute un tag à cette fleur
     */
    public function addTag(Tag $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    /**
     * Retire un tag de cette fleur
     */
    public function removeTag(Tag $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    /**
     * Récupère les commentaires de cette fleur
     * 
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    /**
     * Ajoute un commentaire à cette fleur
     */
    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setFleur($this);
        }

        return $this;
    }

    /**
     * Retire un commentaire de cette fleur
     */
    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            if ($commentaire->getFleur() === $this) {
                $commentaire->setFleur(null);
            }
        }

        return $this;
    }

    /**
     * Calcule la note moyenne de cette fleur
     * 
     * @return float|null La note moyenne ou null si pas de commentaires
     */
    public function getNoteMoyenne(): ?float
    {
        if ($this->commentaires->isEmpty()) {
            return null;
        }

        $total = 0;
        foreach ($this->commentaires as $commentaire) {
            $total += $commentaire->getNote();
        }

        return round($total / $this->commentaires->count(), 1);
    }

    /**
     * Récupère le nombre de commentaires
     */
    public function getNombreCommentaires(): int
    {

templates/fleuriste/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ fleuriste.nom }} - FleurVerte{% endblock %}

{% block body %}
    <div class="container mx-auto px-4 py-8">
        <div class="max-w-4xl mx-auto">
            <div class="bg-white rounded-lg shadow-md overflow-hidden">
                <div class="p-6">
                    <h1 class="text-3xl font-bold mb-4">{{ fleuriste.nom }}</h1>
                    
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                        <div>
                            <h2 class="text-xl font-semibold mb-4">Informations de contact</h2>
                            <div class="space-y-3">
                                {% if fleuriste.adresse %}
                                    <p class="flex items-center">
                                        <span class="material-icons mr-2">location_on</span>
                                        {{ fleuriste.adresse }}
                                    </p>
                                {% endif %}
                                
                                {% if fleuriste.telephone %}
                                    <p class="flex items-center">
                                        <span class="material-icons mr-2">phone</span>
                                        {{ fleuriste.telephone }}
                                    </p>
                                {% endif %}
                                
                                {% if fleuriste.email %}
                                    <p class="flex items-center">
                                        <span class="material-icons mr-2">email</span>
                                        {{ fleuriste.email }}
                                    </p>
                                {% endif %}
                                

                            </div>
                        </div>
                        
                        <div>
                            <h2 class="text-xl font-semibold mb-4">À propos</h2>
                            {% if fleuriste.description %}
                                <p class="text-gray-600">{{ fleuriste.description }}</p>
                            {% else %}
                                <p class="text-gray-500 italic">Aucune description disponible</p>
                            {% endif %}
                            

                        </div>
                    </div>

                    <!-- Section de messagerie pour tous les utilisateurs connectés -->
                    <div class="mt-8 mb-8 text-center">
                        <h2 class="text-2xl font-bold mb-6">Messagerie</h2>
                        <a href="{{ path('app_conversation_new', {'id': fleuriste.id}) }}" class="inline-flex items-center px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition duration-150 ease-in-out text-lg">
                            <i class="fas fa-envelope mr-2"></i> Envoyez un message à {{ fleuriste.nom }}
                        </a>
                    </div>

                    {% if fleuriste.images|length > 0 %}
                        <div class="mt-8">
                            <h2 class="text-2xl font-bold mb-6">Notre magasin en images</h2>
                            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                                {% for image in fleuriste.images %}
                                    <div class="relative group">
                                        <img src="{{ vich_uploader_asset(image, 'imageFile') }}" 
                                             alt="{{ image.caption|default(fleuriste.nom) }}"
                                             class="w-full h-48 object-cover rounded-lg">
                                        {% if image.caption %}
                                            <div class="absolute bottom-0 left-0 right-0 bg-black bg-opacity-50 text-white p-2 rounded-b-lg">
                                                <p class="text-sm">{{ image.caption }}</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}

                    <div class="mt-8">
                        <h2 class="text-2xl font-bold mb-6">Nos fleurs</h2>
                        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                            {% for fleur in fleuriste.fleurs %}
                                <div class="bg-white rounded-lg shadow-md overflow-hidden">
                                    <img src="{{ fleur.imageUrl }}" alt="{{ fleur.nom }}" class="w-full h-48 object-cover">
                                    <div class="p-4">
                                        <h3 class="text-lg font-semibold mb-2">{{ fleur.nom }}</h3>
                                        <p class="text-gray-600">{{ fleur.prix }}€</p>
                                        <a href="{{ path('product_detail', {'id': fleur.id}) }}" 
                                           class="mt-4 inline-block bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600">
                                            Voir détails
                                        </a>
                                    </div>
                                </div>
                            {% else %}
                                <p class="text-gray-500 italic col-span-3 text-center">Aucune fleur disponible pour le moment</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/fleuriste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Fleuristes - FleurVerte{% endblock %}

{% block body %}
	{# Page Fleuristes - Design léger et transparent #}
	<div class="min-h-screen bg-white relative overflow-hidden">
		{# Formes décoratives flottantes #}
		<div class="absolute inset-0 overflow-hidden pointer-events-none">
			<div class="absolute top-20 left-10 w-72 h-72 bg-green-100/40 rounded-full blur-3xl animate-float"></div>
			<div class="absolute top-60 right-10 w-96 h-96 bg-emerald-100/30 rounded-full blur-3xl animate-float-slow"></div>
			<div class="absolute bottom-40 left-1/4 w-64 h-64 bg-teal-100/30 rounded-full blur-3xl animate-float-delay"></div>
			{# Formes florales décoratives #}
			<div class="absolute top-32 right-1/4 text-green-200/30 text-9xl animate-pulse-soft">🌿</div>
			<div class="absolute bottom-20 left-16 text-emerald-200/20 text-8xl animate-float">🌸</div>
			<div class="absolute top-1/2 right-10 text-green-100/25 text-7xl animate-float-slow">🌺</div>
		</div>

		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-16 py-16 relative z-10">
			{# Header #}
			<div class="text-center mb-12">
				<div class="inline-flex items-center gap-2 px-5 py-2 bg-green-50/80 backdrop-blur-sm rounded-full border border-green-100 mb-6">
					<i class="fas fa-store text-green-600"></i>
					<span class="text-green-700 font-medium text-sm">Artisans passionnés</span>
				</div>
				<h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Nos Fleuristes</h1>
				<p class="text-lg text-gray-500 max-w-2xl mx-auto">Découvrez nos artisans fleuristes partenaires, experts passionnés qui cultivent avec amour les plus belles fleurs.</p>
			</div>

			{# Barre de recherche #}
			<div class="max-w-xl mx-auto mb-12">
				<form action="{{ path('app_fleuriste_index') }}" method="get" class="relative">
					<div class="flex items-center bg-white/80 backdrop-blur-sm rounded-2xl border border-gray-200 shadow-lg overflow-hidden hover:shadow-xl transition-shadow">
						<div class="pl-5 text-gray-400">
							<i class="fas fa-search"></i>
						</div>
						<input type="text" name="q" placeholder="Rechercher un fleuriste..." 
							class="flex-1 px-4 py-4 bg-transparent focus:outline-none text-gray-700" 
							value="{{ app.request.query.get('q') }}">
						<button type="submit" class="bg-green-500 hover:bg-green-600 text-white px-6 py-4 font-semibold transition-colors">
							Rechercher
						</button>
					</div>
				</form>
			</div>

			{% if fleuristes is empty and app.request.query.get('q') %}
				{# Message aucun résultat #}
				<div class="max-w-lg mx-auto text-center bg-white/70 backdrop-blur-sm rounded-3xl p-10 border border-white/50 shadow-lg">
					<div class="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6">
						<i class="fas fa-search text-gray-400 text-3xl"></i>
					</div>
					<h3 class="text-xl font-bold text-gray-900 mb-2">Aucun fleuriste trouvé</h3>
					<p class="text-gray-500 mb-6">Aucun résultat pour "{{ app.request.query.get('q') }}"</p>
					<a href="{{ path('app_fleuriste_index') }}" class="inline-flex items-center gap-2 text-green-600 hover:text-green-700 font-semibold">
						<i class="fas fa-arrow-left"></i>
						Voir tous les fleuristes
					</a>
				</div>
			{% else %}
				{# Stats #}
				<div class="flex justify-center gap-6 mb-10">
					<div class="flex items-center gap-2 px-4 py-2 bg-white/60 backdrop-blur-sm rounded-xl border border-white/50 shadow">
						<i class="fas fa-users text-green-600"></i>
						<span class="font-semibold text-gray-700">{{ fleuristes|length }} fleuristes</span>
					</div>
				</div>

				{# Grille des fleuristes #}
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
					{% for user in fleuristes %}
						{% if user.fleuriste %}
							<div class="group bg-white/70 backdrop-blur-sm rounded-3xl border border-white/50 shadow-lg hover:shadow-2xl transition-all duration-500 hover:-translate-y-2 overflow-hidden">
								{# Header avec gradient #}
								<div class="relative h-24 bg-gradient-to-br from-green-400 via-emerald-400 to-teal-400 overflow-hidden">
									<div class="absolute inset-0 opacity-20">
										<div class="absolute top-2 right-4 text-white/30 text-4xl">🌿</div>
										<div class="absolute bottom-2 left-4 text-white/20 text-3xl">🌸</div>
									</div>
								</div>

								{# Avatar #}
								<div class="relative -mt-12 flex justify-center">
									<img src="{{ user.avatarName ? asset('uploads/avatars/' ~ user.avatarName) : asset('basic_avatar/1.png') }}" 
										alt="{{ user.fleuriste.nom }}" 
										class="w-24 h-24 rounded-full object-cover border-4 border-white shadow-lg group-hover:scale-110 transition-transform">
								</div>

								{# Contenu #}
								<div class="p-6 text-center">
									<h3 class="text-xl font-bold text-gray-900 mb-2">{{ user.fleuriste.nom }}</h3>
									
									<div class="space-y-2 mb-6">
										<p class="flex items-center justify-center gap-2 text-gray-500 text-sm">
											<i class="fas fa-envelope text-green-500"></i>
											{{ user.email }}
										</p>
										{% if user.adresses is not empty %}
											{% set principale_adresse = null %}
											{% for adresse in user.adresses %}
												{% if adresse.principale %}
													{% set principale_adresse = adresse %}
												{% endif %}
											{% endfor %}
											{% if principale_adresse is null %}
												{% set principale_adresse = user.adresses|first %}
											{% endif %}
											<p class="flex items-center justify-center gap-2 text-gray-500 text-sm">
												<i class="fas fa-map-marker-alt text-green-500"></i>
												{{ principale_adresse.adresseComplete|length > 30 ? principale_adresse.adresseComplete[:30] ~ '...' : principale_adresse.adresseComplete }}
											</p>
										{% else %}
											<p class="flex items-center justify-center gap-2 text-amber-500 text-sm">
												<i class="fas fa-exclamation-circle"></i>
												Adresse non renseignée
											</p>
										{% endif %}
									</div>

									{# Boutons #}
									<div class="flex gap-3">
										<a href="{{ path('app_fleuriste_detail', {'id': user.id}) }}" 
											class="flex-1 inline-flex items-center justify-center gap-2 bg-green-500 hover:bg-green-600 text-white py-3 px-4 rounded-xl font-semibold transition-all hover:shadow-lg hover:-translate-y-0.5">
											<i class="fas fa-eye"></i>
											Voir
										</a>
										<a href="{{ path('app_conversation_new', {'id': user.id}) }}" 
											class="flex-1 inline-flex items-center justify-center gap-2 bg-white border-2 border-green-500 text-green-600 hover:bg-green-500 hover:text-white py-3 px-4 rounded-xl font-semibold transition-all">
											<i class="fas fa-comment"></i>
											Message
										</a>
									</div>
								</div>
							</div>
						{% endif %}
					{% endfor %}
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}